# This file was generated by GoReleaser. DO NOT EDIT.
cask "relampo" do
  name "relampo"
  desc "Relampo CLI enables recording traffic, scripting load tests, and generating load"
  homepage "https://docs.relampo.dev"
  version "2.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "relampo"

  on_macos do
    on_intel do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_darwin_amd64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "a8d80c197d00c6950f0318cea30c674c8fc2009febfa9e0898b91d366f7b5d05"
    end
    on_arm do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_darwin_arm64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "d13027bb183e86d3ea6430165b50732cef5e182b05104f9698ed813b9fea521f"
    end
  end

  on_linux do
    on_intel do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_linux_amd64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "2c8552a447ac973f5be668c1e9aac5d5f8d60f93c7f29ea46d8cea39c25217b4"
    end
    on_arm do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_linux_arm64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "f2201b62c2895ce1ffeb084dbb15e4c4b75e02101eb0a396ace40ac8c792d47b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/relampo"]
    end
  end

  # No zap stanza required
end
