# This file was generated by GoReleaser. DO NOT EDIT.
cask "relampo" do
  name "relampo"
  desc "Relampo CLI enables recording traffic, scripting load tests, and generating load"
  homepage "https://docs.relampo.dev"
  version "2.3.22"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "relampo"

  on_macos do
    on_intel do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_darwin_amd64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "d9cf47b23dfeb47c03c0069cc0fa73ebcadabca2f2ef736f3cb065c8ab972091"
    end
    on_arm do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_darwin_arm64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "0a04e7cce42b86f14ae57b6e7b010b8f090efc5122fb0936973012f7286c8d77"
    end
  end

  on_linux do
    on_intel do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_linux_amd64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "59b6e13b3ed4b6199a863f2344e88c6443859d6ac56be532778842dcacb207a1"
    end
    on_arm do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_linux_arm64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "76c10d19a26801b1fd086fadd9212c14afde9ee7bdd38889098024c85734c086"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/relampo"]
    end
  end

  # No zap stanza required
end
