# This file was generated by GoReleaser. DO NOT EDIT.
cask "relampo" do
  name "relampo"
  desc "Relampo CLI enables recording traffic, scripting load tests, and generating load"
  homepage "https://docs.relampo.dev"
  version "2.3.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "relampo"

  on_macos do
    on_intel do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_darwin_amd64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "6058f0aa00aac07611c1022e67f15247bd57622dd5d800ba060baac5c8c7b056"
    end
    on_arm do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_darwin_arm64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "0eeda1670b7530f8a78c2a1c5cbda063c35875f8d61edd2fb3c87386bd2cbb23"
    end
  end

  on_linux do
    on_intel do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_linux_amd64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "49a672e8abb740c48a52dba54a487cd6b946e1767ce14ce31ea33ff317eb7994"
    end
    on_arm do
      url "https://dl.relampo.com/relampo/v#{version}/relampo_#{version}_linux_arm64.tar.gz",
        verified: "dl.relampo.com/"
      sha256 "45b377909a66268c7fc81e41ab78a0829b09cdbb133f69cfab788da0325839a9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/relampo"]
    end
  end

  # No zap stanza required
end
